[package]
authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
name = "tableland_worker_runtime"
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
anyhow = "1.0"
bytes = "1"
fp-bindgen-support = { git = "https://github.com/sanderpick/fp-bindgen", features = [
  "async",
  "host",
  "http",
] }
http = "0.2"
once_cell = "1"
rmp-serde = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1"
tableland_client = { path = "../tableland_client" }
tableland_worker_protocol = { path = "../tableland_worker_protocol" }
thiserror = "1.0"
time = { version = "0.3", features = [
  "serde-human-readable",
  "serde-well-known",
  "macros",
] }
tokio = { version = "1.9.0", features = ["rt", "macros"] }
tracing = "0.1.37"
wasmer = { version = "2.3", features = ["compiler", "cranelift", "singlepass"] }
wasmer-wasi = "2.3"

[features]
wasi = []
